<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class UserLocation extends Model
{
    use HasFactory;

    protected $table = 'user_locations';

    /**
     * The attributes that are mass assignable.
     * Note: We do not include 'location_hash' here as it is auto-generated by MySQL.
     */
    protected $fillable = [
        'user_id',
        'state_id',
        'district_id',
        'block_id',
        'panchayat_id',
    ];

    /* -----------------------------------------------------------------
     |  Relationships
     | -----------------------------------------------------------------
     */

    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    public function state(): BelongsTo
    {
        return $this->belongsTo(State::class);
    }

    public function district(): BelongsTo
    {
        return $this->belongsTo(District::class);
    }

    public function block(): BelongsTo
    {
        return $this->belongsTo(Block::class);
    }

    public function panchayat(): BelongsTo
    {
        return $this->belongsTo(Panchayat::class);
    }

    /* -----------------------------------------------------------------
     |  Helper: Get The Specific Assigned Level
     | -----------------------------------------------------------------
     |  Returns the most granular location name assigned to this row.
     |  e.g., if Block is set, returns "Block Name"; if only State, returns "State Name".
     */
    public function getLocationNameAttribute(): string
    {
        if ($this->panchayat_id) return $this->panchayat->name ?? 'Unknown Panchayat';
        if ($this->block_id)     return $this->block->name     ?? 'Unknown Block';
        if ($this->district_id)  return $this->district->name  ?? 'Unknown District';
        return $this->state->name ?? 'Unknown State';
    }

    /**
     * Helper to check the scope/role of this assignment
     */
    public function getScopeAttribute(): string
    {
        if ($this->panchayat_id) return 'Panchayat';
        if ($this->block_id)     return 'Block';
        if ($this->district_id)  return 'District';
        return 'State';
    }
}
